language: node_js
node_js:
  - '0.10'

git:
  depth: 1

before_install:
  - gem update --system
  - gem install compass --no-document
  - gem install tilt  --version "1.4.1" --no-document

before_script:
  - chmod +x .travis/after_success.sh
  - chmod +x ./deploy

script:
  - npm test

branches:
  except:
    - gh-pages

env:
  global:
    - REPO="git@github.com:code4hk/project-hub-mockup"
    - secure: "W1V+UbDUV/FYUdlAAjiF8alLR4QH6vReFIzixZNNmAOnS97LzPT+1s8xtCBRNaKV+HA9hdDPQmD3o70ONpttp2xbpvpFh0w52kMjVm2kqHoJnIw5mOdkjMqmes2eijNznkmtYwk+9FAv1KfWyUukhaSCDdVa5PZ+Jax6p8WanXI="

after_success: .travis/after_success.sh
